// Code generated by goctl. DO NOT EDIT.
// Source: example.proto

package server

import (
	"context"

	"github.com/suyuan32/simple-admin-example-rpc/internal/logic/base"
	"github.com/suyuan32/simple-admin-example-rpc/internal/svc"
	"github.com/suyuan32/simple-admin-example-rpc/types/example"
)

type ExampleServer struct {
	svcCtx *svc.ServiceContext
	example.UnimplementedExampleServer
}

func NewExampleServer(svcCtx *svc.ServiceContext) *ExampleServer {
	return &ExampleServer{
		svcCtx: svcCtx,
	}
}

func (s *ExampleServer) InitDatabase(ctx context.Context, in *example.Empty) (*example.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
