// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"swagger/ent/predicate"
	"swagger/ent/swagger"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SwaggerUpdate is the builder for updating Swagger entities.
type SwaggerUpdate struct {
	config
	hooks    []Hook
	mutation *SwaggerMutation
}

// Where appends a list predicates to the SwaggerUpdate builder.
func (su *SwaggerUpdate) Where(ps ...predicate.Swagger) *SwaggerUpdate {
	su.mutation.Where(ps...)
	return su
}

// Mutation returns the SwaggerMutation object of the builder.
func (su *SwaggerUpdate) Mutation() *SwaggerMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SwaggerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, SwaggerMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SwaggerUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SwaggerUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SwaggerUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SwaggerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(swagger.Table, swagger.Columns, sqlgraph.NewFieldSpec(swagger.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{swagger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SwaggerUpdateOne is the builder for updating a single Swagger entity.
type SwaggerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SwaggerMutation
}

// Mutation returns the SwaggerMutation object of the builder.
func (suo *SwaggerUpdateOne) Mutation() *SwaggerMutation {
	return suo.mutation
}

// Where appends a list predicates to the SwaggerUpdate builder.
func (suo *SwaggerUpdateOne) Where(ps ...predicate.Swagger) *SwaggerUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SwaggerUpdateOne) Select(field string, fields ...string) *SwaggerUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Swagger entity.
func (suo *SwaggerUpdateOne) Save(ctx context.Context) (*Swagger, error) {
	return withHooks[*Swagger, SwaggerMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SwaggerUpdateOne) SaveX(ctx context.Context) *Swagger {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SwaggerUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SwaggerUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SwaggerUpdateOne) sqlSave(ctx context.Context) (_node *Swagger, err error) {
	_spec := sqlgraph.NewUpdateSpec(swagger.Table, swagger.Columns, sqlgraph.NewFieldSpec(swagger.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Swagger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, swagger.FieldID)
		for _, f := range fields {
			if !swagger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != swagger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Swagger{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{swagger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
