// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"swagger/ent/swagger"

	"entgo.io/ent/dialect/sql"
)

// Swagger is the model entity for the Swagger schema.
type Swagger struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Swagger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case swagger.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Swagger", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Swagger fields.
func (s *Swagger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case swagger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Swagger.
// Note that you need to call Swagger.Unwrap() before calling this method if this Swagger
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Swagger) Update() *SwaggerUpdateOne {
	return NewSwaggerClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Swagger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Swagger) Unwrap() *Swagger {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Swagger is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Swagger) String() string {
	var builder strings.Builder
	builder.WriteString("Swagger(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Swaggers is a parsable slice of Swagger.
type Swaggers []*Swagger
