// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"swagger/ent/predicate"
	"swagger/ent/swagger"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SwaggerDelete is the builder for deleting a Swagger entity.
type SwaggerDelete struct {
	config
	hooks    []Hook
	mutation *SwaggerMutation
}

// Where appends a list predicates to the SwaggerDelete builder.
func (sd *SwaggerDelete) Where(ps ...predicate.Swagger) *SwaggerDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SwaggerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, SwaggerMutation](ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SwaggerDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SwaggerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(swagger.Table, sqlgraph.NewFieldSpec(swagger.FieldID, field.TypeInt))
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// SwaggerDeleteOne is the builder for deleting a single Swagger entity.
type SwaggerDeleteOne struct {
	sd *SwaggerDelete
}

// Where appends a list predicates to the SwaggerDelete builder.
func (sdo *SwaggerDeleteOne) Where(ps ...predicate.Swagger) *SwaggerDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *SwaggerDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{swagger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SwaggerDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
