// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MongosColumns holds the columns for the "mongos" table.
	MongosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// MongosTable holds the schema information for the "mongos" table.
	MongosTable = &schema.Table{
		Name:       "mongos",
		Columns:    MongosColumns,
		PrimaryKey: []*schema.Column{MongosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MongosTable,
	}
)

func init() {
}
