// Code generated by ent, DO NOT EDIT.

package swagger

const (
	// Label holds the string label denoting the swagger type in the database.
	Label = "swagger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the swagger in the database.
	Table = "swaggers"
)

// Columns holds all SQL columns for swagger fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
