// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SwaggersColumns holds the columns for the "swaggers" table.
	SwaggersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// SwaggersTable holds the schema information for the "swaggers" table.
	SwaggersTable = &schema.Table{
		Name:       "swaggers",
		Columns:    SwaggersColumns,
		PrimaryKey: []*schema.Column{SwaggersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SwaggersTable,
	}
)

func init() {
}
