// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-example-mongo/ent/mongo"
	"github.com/suyuan32/simple-admin-example-mongo/ent/predicate"
)

// MongoDelete is the builder for deleting a Mongo entity.
type MongoDelete struct {
	config
	hooks    []Hook
	mutation *MongoMutation
}

// Where appends a list predicates to the MongoDelete builder.
func (md *MongoDelete) Where(ps ...predicate.Mongo) *MongoDelete {
	md.mutation.Where(ps...)
	return md
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (md *MongoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, MongoMutation](ctx, md.sqlExec, md.mutation, md.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (md *MongoDelete) ExecX(ctx context.Context) int {
	n, err := md.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (md *MongoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mongo.Table, sqlgraph.NewFieldSpec(mongo.FieldID, field.TypeInt))
	if ps := md.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, md.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	md.mutation.done = true
	return affected, err
}

// MongoDeleteOne is the builder for deleting a single Mongo entity.
type MongoDeleteOne struct {
	md *MongoDelete
}

// Where appends a list predicates to the MongoDelete builder.
func (mdo *MongoDeleteOne) Where(ps ...predicate.Mongo) *MongoDeleteOne {
	mdo.md.mutation.Where(ps...)
	return mdo
}

// Exec executes the deletion query.
func (mdo *MongoDeleteOne) Exec(ctx context.Context) error {
	n, err := mdo.md.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mongo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mdo *MongoDeleteOne) ExecX(ctx context.Context) {
	if err := mdo.Exec(ctx); err != nil {
		panic(err)
	}
}
