// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-example-mongo/ent/mongo"
	"github.com/suyuan32/simple-admin-example-mongo/ent/predicate"
)

// MongoUpdate is the builder for updating Mongo entities.
type MongoUpdate struct {
	config
	hooks    []Hook
	mutation *MongoMutation
}

// Where appends a list predicates to the MongoUpdate builder.
func (mu *MongoUpdate) Where(ps ...predicate.Mongo) *MongoUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// Mutation returns the MongoMutation object of the builder.
func (mu *MongoUpdate) Mutation() *MongoMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MongoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, MongoMutation](ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MongoUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MongoUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MongoUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MongoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(mongo.Table, mongo.Columns, sqlgraph.NewFieldSpec(mongo.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mongo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MongoUpdateOne is the builder for updating a single Mongo entity.
type MongoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MongoMutation
}

// Mutation returns the MongoMutation object of the builder.
func (muo *MongoUpdateOne) Mutation() *MongoMutation {
	return muo.mutation
}

// Where appends a list predicates to the MongoUpdate builder.
func (muo *MongoUpdateOne) Where(ps ...predicate.Mongo) *MongoUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MongoUpdateOne) Select(field string, fields ...string) *MongoUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Mongo entity.
func (muo *MongoUpdateOne) Save(ctx context.Context) (*Mongo, error) {
	return withHooks[*Mongo, MongoMutation](ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MongoUpdateOne) SaveX(ctx context.Context) *Mongo {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MongoUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MongoUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MongoUpdateOne) sqlSave(ctx context.Context) (_node *Mongo, err error) {
	_spec := sqlgraph.NewUpdateSpec(mongo.Table, mongo.Columns, sqlgraph.NewFieldSpec(mongo.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Mongo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mongo.FieldID)
		for _, f := range fields {
			if !mongo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mongo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Mongo{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mongo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
